# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box     = "#{ENV['BOX']}"
  config.vm.box_url = "#{ENV['BOX_URL']}"

  config.vm.guest             = :windows
  config.windows.halt_timeout = 15
  config.vm.communicator      = 'winrm'

  config.winrm.username = 'vagrant'
  config.winrm.password = 'vagrant'

  config.vm.box_check_update = false

  config.vm.synced_folder "../scripts", "/scripts"
  case RUBY_PLATFORM
    when 'i386-mingw32'              then config.vm.synced_folder "C:/Programdata/daas/cache", "/ProgramData/DaaS/cache"
    when 'x64-mingw32'               then config.vm.synced_folder "C:/Programdata/daas/cache", "/ProgramData/DaaS/cache"
    when 'universal.x86_64-darwin14' then config.vm.synced_folder "/var/cache/daas", "/ProgramData/DaaS/cache"
    else config.vm.synced_folder "/var/cache/daas", "/ProgramData/DaaS/cache"
  end

  config.vm.provider :vmware_fusion do |provider, override|
    provider.gui = true
    provider.vmx['memsize']  = '2048'
    provider.vmx['numvcpus'] = '2'
  end

  config.vm.provider :virtualbox do |provider, override|
    provider.gui = true
    provider.customize ['modifyvm', :id, '--ioapic', 'on'] #To assign >1 CPUs
    provider.customize ['modifyvm', :id, '--vram',   30]
    provider.customize ['modifyvm', :id, '--memory', 2048]
    provider.customize ['modifyvm', :id, '--cpus',   2]
  end
end
